function Inversiones() {
    return (
        <section id="inversiones" className="padded">
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id natus at itaque necessitatibus expedita! Cumque, adipisci enim reprehenderit pariatur facere maxime. Quasi atque necessitatibus a ea, accusantium natus quos, repellendus quod magnam veniam id. Eos, iure dolore provident similique vero rem unde quasi, iusto totam quidem ut asperiores id illo ratione illum dicta, nesciunt minima. Maxime, dolor accusamus recusandae dolore repudiandae mollitia, perspiciatis delectus facilis doloribus molestias architecto iure ipsum dicta debitis quisquam consequuntur veniam minus reiciendis. Hic delectus corporis eum alias amet debitis vero aut? Neque ex vero in, unde tenetur cum odio rerum voluptate labore ea facere optio explicabo sapiente nam ducimus deleniti numquam nisi maxime, pariatur dolor sequi ullam, deserunt delectus. Consequatur debitis tenetur tempore veritatis amet.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem facere obcaecati facilis reprehenderit totam recusandae nemo placeat earum, ad magnam, veniam quam pariatur, cumque quas. Ipsam fugit eveniet sequi, exercitationem commodi voluptatibus alias ratione maxime deleniti! Totam, porro laudantium ullam consectetur veniam quisquam expedita voluptatem voluptatum reprehenderit quae esse debitis quod harum sint illo animi dolorum sunt reiciendis. Consequuntur corrupti ab mollitia iusto, blanditiis, harum nulla illum corporis labore accusamus amet. Porro aut temporibus magnam natus odio voluptate neque quod. Quia totam corrupti dolores magnam? Perspiciatis placeat earum perferendis, itaque natus maiores fugit repellendus libero ipsam ratione laborum beatae!</p>
                <p>Qui, magni. Laudantium soluta vero ex. Aperiam officiis eaque quidem dolorum adipisci explicabo consequuntur facere eum. Nihil unde facere ut optio, quaerat recusandae temporibus consectetur cumque explicabo quis nobis ex libero iure nulla. Omnis, totam! Inventore cumque possimus dicta magni fugit quisquam voluptate reiciendis recusandae in, asperiores nisi commodi odit, laudantium iste officia animi. Molestias eius nobis dolorem voluptas, ad incidunt dolorum, unde veniam harum sed ipsa veritatis, vel tempora itaque! Libero dolor recusandae aspernatur, voluptatum expedita laborum, nihil aliquam corporis fugit, accusantium obcaecati dolores omnis magnam. Asperiores fugiat odit, id laboriosam a aliquam aliquid sapiente! Minus voluptatum neque explicabo!</p>
                <p>Corrupti consectetur sunt dicta numquam, impedit repudiandae dolore. Exercitationem sunt nemo ea omnis, quaerat libero illum beatae laboriosam ad veniam deserunt facilis ab vero atque similique explicabo deleniti adipisci nostrum! Aliquid laboriosam sapiente exercitationem officia. Consectetur porro cupiditate repudiandae laudantium iste soluta delectus doloribus! Natus obcaecati sunt odio deleniti laborum adipisci totam eos praesentium odit rem porro esse ad, amet hic perferendis iste, quia nulla quae repellendus molestiae non vel necessitatibus. Repudiandae autem voluptas necessitatibus ipsa tenetur quas quidem culpa distinctio odit, consectetur, aspernatur hic optio in. Nulla asperiores consequuntur eligendi repudiandae dolor in iure quo corporis a? Odit, quam.</p>
                <p>Ea corporis vero aspernatur esse distinctio, eaque eius animi, ex nesciunt modi qui, architecto adipisci quae officia consectetur! Nulla provident, eligendi at consequuntur, fugiat aut veniam laborum pariatur quia velit odio doloremque iure. Ducimus eius eveniet dignissimos, cum porro, accusantium cupiditate ut harum accusamus praesentium asperiores? Iure aspernatur minus amet ut officia atque corrupti? Pariatur deleniti quae explicabo voluptatum, unde asperiores rem molestias quam odio atque dignissimos ducimus repellat ullam vitae hic quos perferendis rerum, necessitatibus quod nihil nesciunt blanditiis nam. Dignissimos molestiae eaque reiciendis consectetur ea deserunt autem, ipsum non culpa repellat et voluptatibus numquam, necessitatibus accusamus ab voluptas!</p>
                <p>Quod soluta beatae eligendi distinctio nemo architecto optio. Eum enim eligendi ipsum aspernatur molestiae illum nulla laboriosam eaque autem totam? Quidem praesentium, at iste fugit quaerat voluptates vitae nam, ab corporis doloremque commodi ut et sequi quis soluta eligendi voluptate deleniti excepturi vero rem recusandae quo numquam sit quas? Eius doloribus accusantium, labore voluptatem temporibus reiciendis consectetur qui enim dicta officia minima ducimus, numquam earum ut maiores blanditiis quo consequuntur nulla! Sit, animi molestiae nobis in ratione accusantium quasi consequatur aliquid, laudantium maxime consequuntur corporis ducimus quae debitis recusandae velit voluptas voluptatum repudiandae dignissimos eaque. Natus maxime animi corporis nobis?</p>
            </div>
        </section>
    )
}

export default Inversiones